export const SET_CATALOG_PRODUCTS = 'SET_CATALOG_PRODUCTS';
export const SET_CATALOG_NEXT_PAGE = 'SET_CATALOG_NEXT_PAGE';
export const SET_CATALOG_PREV_PAGE = 'SET_CATALOG_PREV_PAGE';
export const SET_CATALOG_PAGE = 'SET_CATALOG_PAGE';
export const SET_CATALOG_SORT_BY = 'SET_CATALOG_SORT_BY';
export const SET_CATALOG_LOADING = 'SET_CATALOG_LOADING';
export const SET_CATALOG_INPUT_FILTER_VALUE = 'SET_CATALOG_INPUT_FILTER_VALUE';
export const SET_CATALOG_CHECKBOX_FILTER_VALUE = 'SET_CATALOG_CHECKBOX_FILTER_VALUE';

